open Types.ml

type tech_comp =
  | COMP_none
  | COMP_battle_scanner
  | COMP_ecm_jammer_mark_i
  | COMP_unused_2
  | COMP_deep_space_scanner
  | COMP_battle_computer_mark_ii
  | COMP_unused_5
  | COMP_ecm_jammer_mark_ii
  | COMP_improved_robotic_controls_iii
  | COMP_unused_8
  | COMP_battle_computer_mark_iii
  | COMP_unused_10
  | COMP_ecm_jammer_mark_iii
  | COMP_improved_space_scanner
  | COMP_unused_13
  | COMP_battle_computer_mark_iv
  | COMP_unused_15
  | COMP_ecm_jammer_mark_iv
  | COMP_improved_robotic_controls_iv
  | COMP_unused_18
  | COMP_battle_computer_mark_v
  | COMP_unused_20
  | COMP_ecm_jammer_mark_v
  | COMP_advanced_space_scanner
  | COMP_unused_23
  | COMP_battle_computer_mark_vi
  | COMP_unused_25
  | COMP_ecm_jammer_mark_vi
  | COMP_improved_robotic_controls_v
  | COMP_unused_28
  | COMP_battle_computer_mark_vii
  | COMP_unused_30
  | COMP_ecm_jammer_mark_vii
  | COMP_unused_32
  | COMP_hyperspace_communications
  | COMP_battle_computer_mark_viii
  | COMP_unused_35
  | COMP_ecm_jammer_mark_viii
  | COMP_improved_robotic_controls_vi
  | COMP_unused_38
  | COMP_battle_computer_mark_ix
  | COMP_unused_40
  | COMP_ecm_jammer_mark_ix
  | COMP_unused_42
  | COMP_unused_43
  | COMP_battle_computer_mark_x
  | COMP_oracle_interface
  | COMP_ecm_jammer_mark_x
  | COMP_improved_robotic_controls_vii
  | COMP_technology_nullifier
  | COMP_battle_computer_mark_xi

type tech_cons =
  | CONS_none
  | CONS_reserve_fuel_tanks
  | CONS_unused_1
  | CONS_improved_industrial_tech_9
  | CONS_unused_3
  | CONS_reduced_industrial_waste_80
  | CONS_unused_5
  | CONS_unused_6
  | CONS_improved_industrial_tech_8
  | CONS_unused_8
  | CONS_duralloy_armor
  | CONS_battle_suits
  | CONS_unused_11
  | CONS_improved_industrial_tech_7
  | CONS_automated_repair_system
  | CONS_reduced_industrial_waste_60
  | CONS_unused_15
  | CONS_zortium_armor
  | CONS_improved_industrial_tech_6
  | CONS_unused_18
  | CONS_unused_19
  | CONS_unused_20
  | CONS_unused_21
  | CONS_improved_industrial_tech_5
  | CONS_armored_exoskeleton
  | CONS_reduced_industrial_waste_40
  | CONS_andrium_armor
  | CONS_unused_26
  | CONS_improved_industrial_tech_4
  | CONS_unused_28
  | CONS_unused_29
  | CONS_unused_30
  | CONS_unused_31
  | CONS_improved_industrial_tech_3
  | CONS_tritanium_armor
  | CONS_reduced_industrial_waste_20
  | CONS_advanced_damage_control
  | CONS_unused_36
  | CONS_improved_industrial_tech_2
  | CONS_unused_38
  | CONS_powered_armor
  | CONS_unused_40
  | CONS_adamantium_armor
  | CONS_unused_42
  | CONS_unused_43
  | CONS_industrial_waste_elimination
  | CONS_unused_45
  | CONS_unused_46
  | CONS_unused_47
  | CONS_unused_48
  | CONS_neutronium_armor

type tech_ffld =
  | FFLD_none
  | FFLD_class_i_deflector_shields
  | FFLD_unused_1
  | FFLD_unused_2
  | FFLD_class_ii_deflector_shields
  | FFLD_unused_4
  | FFLD_unused_5
  | FFLD_unused_6
  | FFLD_personal_deflector_shield
  | FFLD_unused_8
  | FFLD_class_iii_deflector_shields
  | FFLD_unused_10
  | FFLD_class_v_planetary_shield
  | FFLD_unused_12
  | FFLD_class_iv_deflector_shields
  | FFLD_unused_14
  | FFLD_repulsor_beam
  | FFLD_unused_16
  | FFLD_unused_17
  | FFLD_unused_18
  | FFLD_class_v_deflector_shields
  | FFLD_personal_absorption_shield
  | FFLD_class_x_planetary_shield
  | FFLD_unused_22
  | FFLD_class_vi_deflector_shields
  | FFLD_unused_24
  | FFLD_unused_25
  | FFLD_cloaking_device
  | FFLD_unused_27
  | FFLD_unused_28
  | FFLD_class_vii_deflector_shields
  | FFLD_zyro_shield
  | FFLD_class_xv_planetary_shield
  | FFLD_unused_32
  | FFLD_class_ix_deflector_shields
  | FFLD_unused_34
  | FFLD_unused_35
  | FFLD_stasis_field
  | FFLD_personal_barrier_shield
  | FFLD_unused_38
  | FFLD_class_xi_deflector_shields
  | FFLD_unused_40
  | FFLD_class_xx_planetary_shield
  | FFLD_black_hole_generator
  | FFLD_class_xiii_deflector_shields
  | FFLD_unused_44
  | FFLD_lightning_shield
  | FFLD_unused_46
  | FFLD_unused_47
  | FFLD_unused_48
  | FFLD_class_xv_deflector_shields

tech_plan =
  | PLAN_none
  | PLAN_ecological_restoration
  | PLAN_improved_terraforming_10
  | PLAN_controlled_barren_environment
  | PLAN_unused_3
  | PLAN_improved_eco_restoration
  | PLAN_controlled_tundra_environment
  | PLAN_unused_6
  | PLAN_improved_terraforming_20
  | PLAN_controlled_dead_environment
  | PLAN_death_spores
  | PLAN_unused_10
  | PLAN_controlled_inferno_environment
  | PLAN_enhanced_eco_restoration
  | PLAN_improved_terraforming_30
  | PLAN_controlled_toxic_environment
  | PLAN_soil_enrichment
  | PLAN_bio_toxin_antidote
  | PLAN_controlled_radiated_environment
  | PLAN_unused_18
  | PLAN_improved_terraforming_40
  | PLAN_cloning
  | PLAN_atmospheric_terraforming
  | PLAN_unused_22
  | PLAN_advanced_eco_restoration
  | PLAN_unused_24
  | PLAN_improved_terraforming_50
  | PLAN_doom_virus
  | PLAN_unused_27
  | PLAN_unused_28
  | PLAN_advanced_soil_enrichment
  | PLAN_unused_30
  | PLAN_improved_terraforming_60
  | PLAN_unused_32
  | PLAN_complete_eco_restoration
  | PLAN_unused_34
  | PLAN_universal_antidote
  | PLAN_unused_36
  | PLAN_improved_terraforming_80
  | PLAN_unused_38
  | PLAN_bio_terminator
  | PLAN_unused_40
  | PLAN_advanced_cloning
  | PLAN_unused_42
  | PLAN_improved_terraforming_100
  | PLAN_unused_44
  | PLAN_unused_45
  | PLAN_unused_46
  | PLAN_unused_47
  | PLAN_unused_48
  | PLAN_complete_terraforming

let prop =
  | PROP_none
  | PROP_retro_engines
  | PROP_unused_1
  | PROP_hydrogen_fuel_cells
  | PROP_unused_3
  | PROP_deuterium_fuel_cells
  | PROP_nuclear_engines
  | PROP_unused_6
  | PROP_unused_7
  | PROP_irridium_fuel_cells
  | PROP_inertial_stabilizer
  | PROP_unused_10
  | PROP_sub_light_drives
  | PROP_unused_12
  | PROP_dotomite_crystals
  | PROP_unused_14
  | PROP_energy_pulsar
  | PROP_unused_16
  | PROP_fusion_drives
  | PROP_uridium_fuel_cells
  | PROP_warp_dissipator
  | PROP_unused_20
  | PROP_unused_21
  | PROP_reajax_ii_fuel_cells
  | PROP_impulse_drives
  | PROP_unused_24
  | PROP_unused_25
  | PROP_intergalactic_star_gates
  | PROP_unused_27
  | PROP_trilithium_crystals
  | PROP_ion_drives
  | PROP_unused_30
  | PROP_unused_31
  | PROP_unused_32
  | PROP_high_energy_focus
  | PROP_unused_34
  | PROP_anti_matter_drives
  | PROP_unused_36
  | PROP_sub_space_teleporter
  | PROP_unused_38
  | PROP_ionic_pulsar
  | PROP_thorium_cells
  | PROP_inter_phased_drives
  | PROP_sub_space_interdiction
  | PROP_unused_43
  | PROP_combat_transporters
  | PROP_inertial_nullifier
  | PROP_unused_46
  | PROP_hyper_drives
  | PROP_unused_48
  | PROP_displacement_device

type weap =
  | WEAP_none
  | WEAP_lasers
  | WEAP_hand_lasers
  | WEAP_unused_2
  | WEAP_hyper_v_rockets
  | WEAP_gatling_laser
  | WEAP_anti_missile_rockets
  | WEAP_neutron_pellet_gun
  | WEAP_hyper_x_rockets
  | WEAP_fusion_bomb
  | WEAP_ion_cannon
  | WEAP_scatter_pack_v_rockets
  | WEAP_ion_rifle
  | WEAP_mass_driver
  | WEAP_merculite_missiles
  | WEAP_neutron_blaster
  | WEAP_anti_matter_bomb
  | WEAP_graviton_beam
  | WEAP_stinger_missiles
  | WEAP_hard_beam
  | WEAP_fusion_beam
  | WEAP_ion_stream_projector
  | WEAP_omega_v_bomb
  | WEAP_anti_matter_torpedoes
  | WEAP_fusion_rifle
  | WEAP_megabolt_cannon
  | WEAP_phasor
  | WEAP_scatter_pack_vii_missiles
  | WEAP_auto_blaster
  | WEAP_pulson_missiles
  | WEAP_tachyon_beam
  | WEAP_hand_phasor
  | WEAP_gauss_autocannon
  | WEAP_particle_beam
  | WEAP_hercular_missiles
  | WEAP_plasma_cannon
  | WEAP_death_ray
  | WEAP_disruptor
  | WEAP_pulse_phasor
  | WEAP_neutronium_bomb
  | WEAP_hellfire_torpedoes
  | WEAP_zeon_missiles
  | WEAP_plasma_rifle
  | WEAP_proton_torpedoes
  | WEAP_scatter_pack_x_missiles
  | WEAP_tri_focus_plasma_cannon
  | WEAP_stellar_converter
  | WEAP_neutron_stream_projector
  | WEAP_mauler_device
  | WEAP_unused_48
  | WEAP_plasma_torpedoes
